wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.22
    code_path: code/src/model/train_video_level.py
    framework: torch
    is_jupyter_run: true
    is_kaggle_kernel: false
    python_version: 3.8.5
    t:
      1:
      - 1
      - 2
      - 3
      4: 3.8.5
      5: 0.10.22
      8:
      - 1
      - 6
bs:
  desc: null
  value: 32
epochs:
  desc: null
  value: 50
patience:
  desc: null
  value: 5
