# Define config dataset
Dataset:
  folder: 'data/raw/yt8m/2' # '/home/jupyter/gcs'
  vocabulary_path: 'data/vocabulary.csv'
  
  parameters:
    N_FEATURES_VIDEO: 1024
    N_FEATURES_AUDIO: 128
    N_CLASSES: 3862

Model:
  folder: 'models'

Train:
  bs: 256
  epochs: 50
  patience: 5