# Define config dataset
Dataset:
  folder: 'data/raw/yt8m_2_full'
  vocabulary_path: 'data/vocabulary.csv'
  feature_level: 'video' # video or frame
  
  parameters:
    N_FEATURES_VIDEO: 1024
    N_FEATURES_AUDIO: 128
    N_CLASSES: 3862

Model:
