# Define config dataset
Dataset:
  folder: 'data/raw/yt8m_2_full'
  vocabulary_path: PATH_VOCABULARY= PATH_ROOT / 'data' / 'raw' / 'yt8m_2nd' / 'vocabulary.csv'
  feature_level: 'video' # video or frame


Model:
